apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argo-cd
spec:
  project: default
  source:
    chart: traefik
    repoURL: https://helm.traefik.io/traefik
    targetRevision: 22.1.0
    helm:
      releaseName: traefik
      values: |
        updateStrategy:
          type: OnDelete

        deployment:
          enabled: true
          kind: DaemonSet

        service:
          enabled: true
          type: NodePort

        ports:
          websecure:
            hostPort: 443
            expose: true
            exposedPort: 443
            protocol: TCP

        # Suggestion to solve eternal ingress progressing inside ArgoCD
        # https://github.com/argoproj/argo-cd/issues/1704#issuecomment-1131903042
        additionalArguments:
          - "--providers.kubernetesingress.ingressendpoint.publishedservice=traefik/traefik"

  destination:
    server: "https://kubernetes.default.svc"
    namespace: traefik
  
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true